service: drexler-token-generator

provider:
  name: aws
  runtime: nodejs6.10
  versionFunctions: false

functions:
  createToken:
    handler: src/token-service.createToken
    events: # endpoint triggering lambda
      - http:
          path: /token
          method: post
  createJwt:
    handler: src/token-service.createJwt
    events: # endpoint triggering lambda
      - http:
          path: /jwt
          method: post
          cors: true

plugins:
  - serverless-webpack

custom:
  webpack: ./webpack.config.js
  webpackIncludeModules: true
