service: drexler-token-generator

provider:
  name: aws
  runtime: nodejs6.10

functions:
  createToken:
    handler: src/token-service.createToken
    events: # endpoint triggering lambda
      - http:
          path: /token
          method: post

plugins:
  - serverless-webpack

custom:
  webpack: ./webpack.config.js
  webpackIncludeModules: true
