service: sso-drexler-token

provider:
  name: aws
  runtime: nodejs6.10

functions:
  createToken:
    handler: tokens-service.create


plugins:
  - serverless-webpack

custom:
  webpack: ./webpack.config.js
  webpackIncludeModules: true
